version: '3.7'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  data:
